name: Se Dedicated Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Game version string'
        required: true
        type: string

jobs:
  Main:
    name: Build Nuget Package
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - uses: nuget/setup-nuget@v2
        with:
          nuget-version: '5.x'
      - name: Download Depot tool
        run: wget https://github.com/SteamRE/DepotDownloader/releases/download/DepotDownloader_3.0.0/DepotDownloader-framework.zip -O tool.zip && 7z x tool.zip -o./tool && rm tool.zip
      - name: Download Steam Dlls
        run: dotnet ./tool/DepotDownloader.dll -app 298740 -depot 298741 -os windows -dir . -filelist dedi_dlls_list.txt
      - name: Prepare folder structure
        run: mkdir -p ./nuget/lib/net48
      - name: Copy binaries
        run: cp ./DedicatedServer64/* ./nuget/lib/net48
      - name: Create Nuget Package
        run: nuget pack specs/SpaceEngineersDedicated.ReferenceAssemblies.nuspec -BasePath ./nuget -Version ${{ inputs.version }}  -NonInteractive -NoPackageAnalysis -OutputFileNamesWithoutVersion
      - name: Install Sleet
        run: dotnet tool install -g sleet --version 5.1.3
      - name: Push Nuget Package
        env:
          SLEET_FEED_TYPE: s3
          SLEET_FEED_PATH: https://nuget.storage.yandexcloud.net
          SLEET_FEED_BUCKETNAME: nuget
          SLEET_FEED_SERVICEURL: https://storage.yandexcloud.net
          SLEET_FEED_ACCESSKEYID: ${{ secrets.S3_KEY_ID }}
          SLEET_FEED_SECRETACCESSKEY: ${{ secrets.S3_KEY }}
        run: sleet push ./SpaceEngineersDedicated.ReferenceAssemblies.nupkg
